// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlJMnqu1IMuSYcfA-ueBwoRHvzFpBAW_I',
    appId: '1:1077724472159:web:a65a54c712d9043afaccea',
    messagingSenderId: '1077724472159',
    projectId: 'mynotesdaviesapp',
    authDomain: 'mynotesdaviesapp.firebaseapp.com',
    storageBucket: 'mynotesdaviesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd41kOnRvB-8IcfkYdaqObL1QbN-jV3i0',
    appId: '1:1077724472159:android:134c11f23a94cce3faccea',
    messagingSenderId: '1077724472159',
    projectId: 'mynotesdaviesapp',
    storageBucket: 'mynotesdaviesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJD6Ce4p1Nqzb9XJa2qDzdbqDX2C75mQQ',
    appId: '1:1077724472159:ios:79b80dececc1b1c1faccea',
    messagingSenderId: '1077724472159',
    projectId: 'mynotesdaviesapp',
    storageBucket: 'mynotesdaviesapp.appspot.com',
    iosClientId: '1077724472159-oqevp7t87og04ag6i8i1d2qbio56dse4.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJD6Ce4p1Nqzb9XJa2qDzdbqDX2C75mQQ',
    appId: '1:1077724472159:ios:4963438b61039833faccea',
    messagingSenderId: '1077724472159',
    projectId: 'mynotesdaviesapp',
    storageBucket: 'mynotesdaviesapp.appspot.com',
    iosClientId: '1077724472159-lppamrh626cr512m0fif9ubi4eiu3d4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
